# Generated by Django 5.1.4 on 2024-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_favorite_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied_jobs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
