# Generated by Django 5.1.4 on 2024-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_hourly_rate_alter_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
