# Generated by Django 5.1.4 on 2024-12-23 07:51

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_id',
            field=models.CharField(default=applications.models.generate_app_id, editable=False, max_length=8, unique=True),
        ),
    ]
