# Generated by Django 5.1.4 on 2024-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desirable_skills',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='55549906', editable=False, max_length=8, unique=True),
        ),
    ]
