# Generated by Django 5.1.4 on 2024-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_desirable_skills_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='e9e11c0f', editable=False, max_length=8, unique=True),
        ),
    ]
