# Generated by Django 5.1.4 on 2024-12-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_job_id'),
        ('users', '0007_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='4f1f942d', editable=False, max_length=8, unique=True),
        ),
    ]
