# Generated by Django 5.1.4 on 2024-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_company_alter_job_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='1bf84165', editable=False, max_length=8, unique=True),
        ),
    ]
